kind: BuildConfig
apiVersion: v1
metadata:
  name: index-blog-entries
  labels:
    app: solr-indexing
spec:
  resources:
    requests:
      cpu: 2000Mi
      memory: 1G
  runPolicy: Parallel
  source:
    git:
      ref: master
      uri: "https://github.com/alacambra/blog-build.git"
    type: Git
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: index_blog.Jenkinsfile