= Use H2 for fast Integration Test 
Albert Lacambra Basil 
:jbake-title: Use H2 for fast Integration Test 
:description: Use H2 as database for Integration Test and make to tun it as fast as Unit Test 
:jbake-date: 2020-02-11 
:jbake-type: post 
:jbake-status: draft 
:jbake-tags: java, testing, h2, jpa
:doc-id: use-h2-for-fast-integration-test 

== Use H2 on memory with Hibernate

- Add maven dependencies. H2 on meory database and hibernate entiy manager:
[source, xml]
----
<dependency>
    <groupId>com.h2database</groupId>
    <artifactId>h2</artifactId>
    <version>1.4.197</version>
    <scope>test</scope>
</dependency>

<dependency>
    <groupId>org.hibernate</groupId>
    <artifactId>hibernate-entitymanager</artifactId>
    <version>5.3.7.Final</version>
    <scope>test</scope>
</dependency>
----

- create persitance.xml file with dsesired params on _src/test/resources/META-INF/persistence.xml_:
[source, xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<persistence version="2.1" xmlns="http://xmlns.jcp.org/xml/ns/persistence"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/persistence http://xmlns.jcp.org/xml/ns/persistence/persistence_2_1.xsd">

<persistence-unit name="{{db-schema}}" transaction-type="RESOURCE_LOCAL">
    <properties>
        <property name="hibernate.show_sql" value="false"/>
        <property name="hibernate.connection.pool_size" value="10"/>
        <property name="javax.persistence.jdbc.url" value="jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"/>
        <property name="javax.persistence.jdbc.driver" value="org.h2.Driver"/>
        <property name="javax.persistence.schema-generation.database.action" value="drop-and-create"/>
        <property name="javax.persistence.validation.mode" value="none"/>
    </properties>
</persistence-unit>
----

== Create an EntityManagerFactory only once

To load a new _EntityManagerFactory_ assures that each test will receive a fresh database. However, each test will have a time penalizations that can be of seconds. 

To make it faster, just assure to only load one _EntityManagerFactory_ for all test. Each test will load now a new EntityManager without the DB inititialization penalization.

We can create an _EntityManagerFactory_ as static variable:

[source, java]
----
public class PersistenceContextHelper {

    private static EntityManagerFactory entityManagerFactory;
    
    public static EntityManagerFactory getEntityManagerFactory() {
        if (entityManagerFactory == null) {
        entityManagerFactory = Persistence.createEntityManagerFactory("schema");
        }
    }
}
----

Now, if we want to have an empty databese before each testwe need to clean the database. That means:

* Delete all existent entities:
. Disable referencia integrity or foreign key constraints: *SET REFERENTIAL_INTEGRITY FALSE*
. Get all jpa entities types.
. Delete all entites from each type

* Restart all sequences:
. Find all sequences: *SELECT * FROM INFORMATION_SCHEMA.SEQUENCES*
. Restart de sequence: *ALTER SEQUENCE {{seqName}} RESTART WITH 1*

[source, java]
----
public static void deleteAllEntities(EntityManager em) {

    //Commit active transaction
    if (em.getTransaction().isActive()) {
        em.getTransaction().commit();
    }

    em.getTransaction().begin();

    //Disable Referential Integrity on H2
    em.createNativeQuery("SET REFERENTIAL_INTEGRITY FALSE").executeUpdate();

    //Discover all JPA entities types
    for (EntityType<?> entity : em.getMetamodel().getEntities()) {

        //Delete all existent entities entries
        final String className = entity.getName();
        Query q = em.createQuery("delete from " + className + " c");
        q.executeUpdate();
    }

    //Restart all sequences:
    //Get all existent sequences
    List<Object[]> sequences = em.createNativeQuery("SELECT * FROM INFORMATION_SCHEMA.SEQUENCES").getResultList();

    for (Object[] s : sequences) {
        String seqName = (String) s[2];
        //Restart all sequences to value 1
        em.createNativeQuery("ALTER SEQUENCE " + seqName + " RESTART WITH 1").executeUpdate();
    }

    em.getTransaction().commit();
    em.clear();
}
----

[CAUTION] Take care that the above code should not be used in any multithreading test.




