= Java Reflexion basics. Get and execute methods
Albert Lacambra Basil
:jbake-title: Java Reflexion basics. Get and execute methods
:description: How to find and execute methods of an object using reflexion
:jbake-date: 2019-10-28
:jbake-type: post
:jbake-status: published
:jbake-tags: java
:doc-id: java-reflexion-basics-1-get-and-execute-methods

== Example class MyClass
[source, java]
--
package tech.lacambra.reflexion;

public class MyClass {
  private String str = "some value";
  public void methodA() {}
  private void privateMethodB() {}
  public String getStr() { return str; }
  public String getStr(String append) { return append + str; }
}
--

== Get a method of a class
[source, java]
--
Method methodA = MyClass.class.getMethod("methodA");
--

== Execute a method of a class
[source, java]
--
MyClass myClassInstance = new MyClass();
methodA.invoke(myClassInstance);
--

== Get and execute a private method of a class
[source, java]
--
Method privateMethodB = MyClass.class.getDeclaredMethod("privateMethodB");
privateMethodB.setAccessible(true);
privateMethodB.invoke(myClassInstance);
--

== Execute a method with params
[source, java]
--
String result = (String) myClassInstance.getClass()
    .getMethod("getStr", String.class)
    .invoke(myClassInstance, "toAppend");

assertEquals("toAppendsome value", result);
--

== Use a helper to get and assign returned values
[source, java]
--
public static <T> T getValue(String methodName, Object instance) throws NoSuchMethodException, InvocationTargetException, IllegalAccessException {
    return (T) instance.getClass().getMethod(methodName).invoke(instance);
}
....
String myString = getValue("getStr", new MyClass());
--
