= Useful bash commands
Albert Lacambra Basil
:jbake-title: Useful bash commands
:description: Som command examples using AWK, sed, find, watch and aria2
:jbake-date: 2019-11-04
:jbake-type: post
:jbake-status: published
:jbake-tags: commands-and-tools
:doc-id: useful-commands-1

== Reset console colors to bash

[source, bash]
--
echo -e "\033[0m"
--

== AWK useful commands

print column **n** using a separator **#**:
[source, bash]
--
awk -F# '{print $n}'
--

print column 3 of lines that start with a number:
[source, bash]
--
awk '/^[0-9]/ {print $3}'
--

=== Variables:
**NF**: number of fields

**NR**: Number of record being processed


=== Avoid first record(row) and print last field (columnd):
[source, bash]
--
awk '{if(NR>1) print $NF}': 
--

More about built-in variables: link:https://www.thegeekstuff.com/2010/01/8-powerful-awk-built-in-variables-fs-ofs-rs-ors-nr-nf-filename-fnr/?ref=binfind.com/web[8 Powerful Awk Built-in,window=_blank]

Some more tricks link:https://twitter.com/b0rk/status/1000604334026055681[here,window=_blank]

== Match and replace using sed
[source, bash]
--
sed -i -e ‘s/pattern/replace-for/g'
--

link:https://www.gnu.org/software/sed/manual/sed.html[Sed website,window=_blank]


== Apply commands using find

Execute rm on *.class files:
[source, bash]
--
find . -name *.class -type f -exec rm;
--

Execute the sed param on files containing java in the name:
[source, bash]
--
find . -type f |grep java|xargs sed -i -e ‘s/pattern/replace-for/g'
--


== Rerun command using watch

To rerun automatically a command use:

[source, bash]
--
watch -n 1 --differences {COMMAND TO REFRESH}
--

For example, to see creation of docker containers:

[source, bash]
--
watch -n 1 --differences docker ps
--

== Aria2, the wget alternative	

Aria2 offers interesting options to download a file, like parallel downloading:

[source, bash]
--
aria2c -x4 {utl} to use 4 connections
--

More info: https://aria2.github.io/

== ps

Shows process info

.ps aux: Shows process and resources info
[source, bash]
----
USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root          1  1.2  0.0 196748  9872 ?        Ss   May14 276:11 /usr/lib/systemd/systemd --switched-root --system --deserialize 22
root          2  0.0  0.0      0     0 ?        S    May14   0:00 [kthreadd]
root          4  0.0  0.0      0     0 ?        S<   May14   0:00 [kworker/0:0H]
root          6  0.0  0.0      0     0 ?        S    May14   0:16 [ksoftirqd/0]
root          7  0.0  0.0      0     0 ?        S    May14   0:01 [migration/0]
root          8  0.0  0.0      0     0 ?        S    May14   0:00 [rcu_bh]
root          9  0.2  0.0      0     0 ?        S    May14  49:53 [rcu_sched]
root         10  0.0  0.0      0     0 ?        S<   May14   0:00 [lru-add-drain]
root         11  0.0  0.0      0     0 ?        S    May14   0:03 [watchdog/0]
----

Where _VSZ_ is process' claimed memory and _RSS_ is actual process' used memory

.ps fax: shows proecess relations through tree structure
[source, bash]
----
 PID TTY      STAT   TIME COMMAND
    2 ?        S      0:00 [kthreadd]
    4 ?        S<     0:00  \_ [kworker/0:0H]
    6 ?        S      0:16  \_ [ksoftirqd/0]
    7 ?        S      0:01  \_ [migration/0]
    8 ?        S      0:00  \_ [rcu_bh]
    9 ?        S     49:53  \_ [rcu_sched]
----

.free -m: information about mmory usage. Shown in MB.
[source, bash]
----
$ free -m
              total        used        free      shared  buff/cache   available
Mem:          63881       25985        3109          23       34786       37331
Swap:             0           0           0
----

[NOTE]
====
*total*: total memory
*used*: total used memory
*free*: total not used _at all_ memory
*buff*: files in ram in write mode that must be commited to disk
*cache*: files used by a process that are keep in RAM as long as possible. If memory is needed cache is gonna be removed.
*available*: _free_ memory plus _cached_ memory that can be released. Is the *real* memory available for new proceses
====

.cat /proc/meminfo: detailed information about how the kernel is using memory.
[source, bash]
----
$ cat /proc/meminfo
MemTotal:       65414256 kB
MemFree:         3190512 kB
MemAvailable:   38263776 kB
Buffers:            4732 kB
Cached:         28185504 kB
SwapCached:            0 kB
Active:         35894232 kB
----

[NOTE]
====
Interesting fields from *meminfo*:

*Active*:         Memory being used

*Inactive*:       Memory idle for a while

*Active*(*anon*):   Memory allocated by processes phisically in RAM

*Inactive*(*anon*): Memory idle in RAM. If the kernel needs more 
memory, this one is gonna be moved to *swap*

*Active*(file):   Active cached memory

*Inactive*(file): Inactive cached memory
====

uptime: running time of the system plus *load avarage*.

[NOTE]
====
*load average*: 0.93, 0.75, 1.15
The numbers are the avarage amount of processes that have been running in a given time.

E.g. Means that 1 code has been busy in avarge the las minute, 0.75 for the las 5 minutes and 1.15 the las 15 minutes
====

.lscpu: shows cpu ingo
[source, bash]
----
$ lscpu |head
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                20
On-line CPU(s) list:   0-19
Thread(s) per core:    2
Core(s) per socket:    10
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
....
----

[TIP]
====
*load avarage* should not be getting over the *number of CPUs*. That would means that the system is operating over its capacity
====