kind: BuildConfig
apiVersion: v1
metadata:
  name: jenkins-vars
  labels:
    app: jenkins-vars
spec:
  resources:
    requests:
      cpu: 2000Mi
      memory: 1G
  runPolicy: Parallel
  source:
    git:
      ref: master
      uri: "https://github.com/alacambra/blog-build.git"
    type: Git
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: jbake-blog/assets/blog/2020/jenkinsfile-variables/Jenkinsfile